# Generated by Django 2.2.24 on 2021-06-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20210628_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_recruiter',
        ),
    ]
