# Generated by Django 2.2.24 on 2021-06-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=25)),
                ('county', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.CharField(max_length=40)),
            ],
        ),
    ]
